---
name: AutomatePythonTests

on:
  push :
  
  workflow_dispatch:



jobs:
  Execute_Script:
    runs-on: [self-hosted]
    strategy:
      fail-fast: false
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run script
        run: premier-essaie/amg-master/Debug/amg.exe

    